version: '3.8'

services:
  rug-app:
    build: .
    container_name: rug_container
    ports:
      - "8081:8081" # Metro Bundler
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    # CHANGED: This command keeps the container running forever so we can exec into it
    command: tail -f /dev/null
